context("make_parameters")

test_that("replace leafpar defaults works", {
  expect_error(make_leafpar(replace = list(abs_s = 1)))
  expect_error(make_leafpar(replace = list(abs_l = 1)))
  expect_error(make_leafpar(replace = list(g_xc = 1)))
  expect_error(make_leafpar(replace = list(g_ic = 1)))
  expect_error(make_leafpar(replace = list(g_uw = 1)))
  expect_error(make_leafpar(replace = list(k_x = 1)))
  expect_error(make_leafpar(replace = list(V_cmax = 1)))
  expect_error(make_leafpar(replace = list(J_max = 1)))
  expect_error(make_leafpar(replace = list(R_d = 1)))
  expect_error(make_leafpar(replace = list(K_c = 1)))
  expect_error(make_leafpar(replace = list(K_o = 1)))
  expect_error(make_leafpar(replace = list(gamma_star = 1)))
  expect_error(make_leafpar(replace = list(g_sw = 1)))
  expect_error(make_leafpar(replace = list(leafsize = 1)))
  expect_error(make_leafpar(replace = list(sr = 1)))
  
  expect_identical(make_leafpar(replace = list(abs_s = set_units(1, unitless)))$abs_s,
                   set_units(1, unitless))
  # leaf_par <- make_leafpar(replace = list(abs_l = set_units(1, unitless)))
  # leaf_par <- make_leafpar(replace = list(g_xc = set_units(1, mol / (m^2 * s * Pa))))
  # leaf_par <- make_leafpar(replace = list(g_ic = set_units(1, mol / (m^2 * s * Pa))))
  # leaf_par <- make_leafpar(replace = list(g_uw = set_units(1, mol / (m^2 * s * Pa))))
  # leaf_par <- make_leafpar(replace = list(k_x = set_units(1, unitless)))
  # leaf_par <- make_leafpar(replace = list(V_cmax = set_units(1, umol / (m^2 * s))))
  # leaf_par <- make_leafpar(replace = list(J_max = set_units(1, umol / (m^2 * s))))
  # leaf_par <- make_leafpar(replace = list(R_d = set_units(1, umol / (m^2 * s))))
  # leaf_par <- make_leafpar(replace = list(K_c = set_units(1, Pa)))
  # leaf_par <- make_leafpar(replace = list(K_o = set_units(1, kPa)))
  # leaf_par <- make_leafpar(replace = list(gamma_star = set_units(1, Pa)))
  # leaf_par <- make_leafpar(replace = list(g_sw = set_units(1, mol / (m^2 * s * Pa))))
  # leaf_par <- make_leafpar(replace = list(leafsize = set_units(1, m)))
  # leaf_par <- make_leafpar(replace = list(sr = set_units(1, unitless)))
  
})
